creation_timestamp: 1768239459515
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768239459515
model_id: m-ae5f8e8e2dbc496db5e713b22f80fddf
name: weather-forecaster
run_id: 7dd08d7b7cae4fb3acc0ec4f9b0fe948
run_link: ''
source: models:/m-ae5f8e8e2dbc496db5e713b22f80fddf
status: READY
status_message: null
storage_location: mlflow-artifacts:/382474715181360815/models/m-ae5f8e8e2dbc496db5e713b22f80fddf/artifacts
user_id: null
version: 16
