creation_timestamp: 1768237461261
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768237461261
model_id: m-8182f1a8c0e54ac7923fd6b9bbdc91cd
name: weather-forecaster
run_id: 03193b74c8ad4f13912cdb4ed8cdbdc4
run_link: ''
source: models:/m-8182f1a8c0e54ac7923fd6b9bbdc91cd
status: READY
status_message: null
storage_location: mlflow-artifacts:/382474715181360815/models/m-8182f1a8c0e54ac7923fd6b9bbdc91cd/artifacts
user_id: null
version: 6
