creation_timestamp: 1768239187952
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768239187952
model_id: m-f82dad99fde142fcbc736a71aa3413b7
name: weather-forecaster
run_id: 1e0c509a56fe45ff9c9598af4d4b5c02
run_link: ''
source: models:/m-f82dad99fde142fcbc736a71aa3413b7
status: READY
status_message: null
storage_location: mlflow-artifacts:/382474715181360815/models/m-f82dad99fde142fcbc736a71aa3413b7/artifacts
user_id: null
version: 13
