creation_timestamp: 1768235656236
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768235656236
model_id: m-1068aa7ed83f44a9b5bfbed02bc4209a
name: weather-forecaster
run_id: 07bff33e939142ecb86cd253a230c123
run_link: ''
source: models:/m-1068aa7ed83f44a9b5bfbed02bc4209a
status: READY
status_message: null
storage_location: mlflow-artifacts:/382474715181360815/models/m-1068aa7ed83f44a9b5bfbed02bc4209a/artifacts
user_id: null
version: 2
