creation_timestamp: 1768239448820
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1768239448820
model_id: m-8c5ededf9fcc4d0daad9575313287fc2
name: weather-forecaster
run_id: a411bed6824c4631b901662d9d79d685
run_link: ''
source: models:/m-8c5ededf9fcc4d0daad9575313287fc2
status: READY
status_message: null
storage_location: mlflow-artifacts:/382474715181360815/models/m-8c5ededf9fcc4d0daad9575313287fc2/artifacts
user_id: null
version: 15
